### ISSUE TITLE
Content to add to website

### ISSUE THREAD

**Issue by Alexandria** [codeforkansascity/hackkc-2018#30]
- [x] Cover the basics - Who, What, Where, When, How, Why (I think we’ve got this content for Aug 11)
- [ ] Make it very clear that the Aug 11 event is to start developing projects for participation in HackKC
- [x] Update the page name - The event name is “Discovery and Design Workshop” which is how we are participating in National Day of Civic Hacking (NDoCH). On the Eventbrite this is noted by stating “Discovery and Design Workshop (on the National Day of Civic Hacking)” As is, it looks like the event is *called* National Day of Civic Hacking
- [ ] Aug 11 - Discovery and Design Workshop - Prominently display this event, but still have content about HackKC, and be clear that this event is part of getting ready *for* HackKC
- [ ] Clarify target audience - Make it clear that Oct 13/14 is for coders looking to jump in and code, and Aug 11 is for anyone (coders or not) that want to contribute to project ideas/planning
- [ ] Update the look & function of the page (edited)
- [ ] Write a FAQ section.

**Comment by zmon** [comment]
# FAQ

* Should I attend Discovery and Design workshop ?

* What Should I Bring?

* Will there be food?

* I do not know how to code can I still come?

* How do I submit a project?

* Where will it be?

* Where do I park ?
